import type { Vendor, MarketEvent, VendorRegistration, Testimonial, ProduceBoxItem, FAQItem } from '@/types'

export const vendors: Vendor[] = [
  {
    id: '1',
    business_name: 'Sunrise Organics',
    slug: 'sunrise-organics',
    description: 'We\'ve been growing certified organic vegetables for over 15 years on our family farm just outside the city. From heirloom tomatoes to crisp salad greens, everything we bring to market was picked fresh that morning. We believe food should nourish both the body and the community.',
    category: 'produce',
    contact_email: 'hello@sunriseorganics.com',
    contact_phone: '(555) 123-4567',
    website_url: 'https://sunriseorganics.com',
    logo_url: null,
    social_instagram: '@sunriseorganics',
    social_facebook: 'https://facebook.com/sunriseorganics',
    is_active: true,
    is_featured: true,
    created_at: '2025-01-15T10:00:00Z',
    updated_at: '2025-01-15T10:00:00Z',
  },
  {
    id: '2',
    business_name: 'Golden Crust Bakery',
    slug: 'golden-crust-bakery',
    description: 'Artisan breads and pastries baked with locally milled flour and organic butter. Our sourdough starter is over 20 years old, and every loaf tells a story. Come early on market day — our cinnamon rolls sell out before noon!',
    category: 'baked_goods',
    contact_email: 'orders@goldencrust.com',
    contact_phone: '(555) 234-5678',
    website_url: 'https://goldencrust.com',
    logo_url: null,
    social_instagram: '@goldencrustbakes',
    social_facebook: null,
    is_active: true,
    is_featured: true,
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2025-02-01T10:00:00Z',
  },
  {
    id: '3',
    business_name: 'Meadowbrook Dairy',
    slug: 'meadowbrook-dairy',
    description: 'Small-batch artisan cheeses and farm-fresh milk from our grass-fed herd. We make everything from creamy chèvre to aged cheddar right on the farm. Our cows are treated like family — because they are.',
    category: 'dairy',
    contact_email: 'info@meadowbrookdairy.com',
    contact_phone: '(555) 345-6789',
    website_url: null,
    logo_url: null,
    social_instagram: '@meadowbrookdairy',
    social_facebook: 'https://facebook.com/meadowbrookdairy',
    is_active: true,
    is_featured: true,
    created_at: '2025-01-20T10:00:00Z',
    updated_at: '2025-01-20T10:00:00Z',
  },
  {
    id: '4',
    business_name: 'Petal & Stem',
    slug: 'petal-and-stem',
    description: 'Locally grown seasonal flowers and hand-tied bouquets that bring the beauty of the garden to your table. We grow over 50 varieties of cut flowers using sustainable practices — no synthetic chemicals, just sunshine and love.',
    category: 'flowers',
    contact_email: 'bloom@petalandstem.com',
    contact_phone: '(555) 456-7890',
    website_url: 'https://petalandstem.com',
    logo_url: null,
    social_instagram: '@petalandstem',
    social_facebook: null,
    is_active: true,
    is_featured: true,
    created_at: '2025-02-10T10:00:00Z',
    updated_at: '2025-02-10T10:00:00Z',
  },
  {
    id: '5',
    business_name: 'Abuela\'s Kitchen',
    slug: 'abuelas-kitchen',
    description: 'Authentic tamales, salsas, and prepared foods made from family recipes passed down through four generations. Every jar of salsa and every tamale is made by hand with the freshest local ingredients we can find.',
    category: 'prepared_food',
    contact_email: 'hola@abuelaskitchen.com',
    contact_phone: '(555) 567-8901',
    website_url: null,
    logo_url: null,
    social_instagram: '@abuelaskitchen',
    social_facebook: 'https://facebook.com/abuelaskitchen',
    is_active: true,
    is_featured: false,
    created_at: '2025-03-01T10:00:00Z',
    updated_at: '2025-03-01T10:00:00Z',
  },
  {
    id: '6',
    business_name: 'Honeycomb Apiary',
    slug: 'honeycomb-apiary',
    description: 'Raw, unfiltered honey harvested from our hives throughout the seasons. Each batch carries the unique flavor of whatever our bees were foraging — wildflower, clover, blackberry, and more. We also offer beeswax candles and lip balms.',
    category: 'produce',
    contact_email: 'buzz@honeycombapiary.com',
    contact_phone: null,
    website_url: 'https://honeycombapiary.com',
    logo_url: null,
    social_instagram: '@honeycombapiary',
    social_facebook: null,
    is_active: true,
    is_featured: false,
    created_at: '2025-02-15T10:00:00Z',
    updated_at: '2025-02-15T10:00:00Z',
  },
  {
    id: '7',
    business_name: 'River Clay Studios',
    slug: 'river-clay-studios',
    description: 'Handcrafted pottery and ceramics inspired by the natural landscape. From functional dinner sets to decorative vases, each piece is wheel-thrown and glazed by hand in our riverside studio. Perfect for bringing artisan beauty to your everyday.',
    category: 'crafts',
    contact_email: 'create@riverclay.com',
    contact_phone: '(555) 678-9012',
    website_url: 'https://riverclaystudios.com',
    logo_url: null,
    social_instagram: '@riverclaystudios',
    social_facebook: 'https://facebook.com/riverclaystudios',
    is_active: true,
    is_featured: false,
    created_at: '2025-03-10T10:00:00Z',
    updated_at: '2025-03-10T10:00:00Z',
  },
  {
    id: '8',
    business_name: 'Green Acres Farm',
    slug: 'green-acres-farm',
    description: 'Family-run farm specializing in seasonal berries, stone fruits, and preserves. Our u-pick berry fields are a summer tradition, and our jams and preserves let you enjoy the harvest all year long.',
    category: 'produce',
    contact_email: 'farm@greenacres.com',
    contact_phone: '(555) 789-0123',
    website_url: null,
    logo_url: null,
    social_instagram: '@greenacresfarm',
    social_facebook: null,
    is_active: true,
    is_featured: true,
    created_at: '2025-01-25T10:00:00Z',
    updated_at: '2025-01-25T10:00:00Z',
  },
]

export const events: MarketEvent[] = [
  {
    id: '1',
    title: 'Saturday Market - Spring Kickoff',
    slug: 'saturday-market-spring-kickoff',
    description: 'Join us for the grand opening of the spring market season! We\'re kicking things off with live music from local bands, cooking demos, and a special kids\' activity corner. Over 25 vendors will be on hand with the freshest spring produce, baked goods, flowers, and more.',
    event_date: '2026-03-07',
    start_time: '09:00',
    end_time: '14:00',
    location: 'Market on 41st - Corner of 41st & Elm',
    max_vendors: 30,
    is_published: true,
    is_cancelled: false,
    special_theme: 'Spring Kickoff',
    image_url: null,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
    vendor_count: 22,
  },
  {
    id: '2',
    title: 'Saturday Market - Berry Festival',
    slug: 'saturday-market-berry-festival',
    description: 'It\'s berry season! This week\'s market celebrates all things berry — strawberries, blueberries, raspberries, and more. Enjoy berry-themed treats from our bakers, fresh berry bouquets, and a berry pie contest. Come hungry!',
    event_date: '2026-03-14',
    start_time: '09:00',
    end_time: '14:00',
    location: 'Market on 41st - Corner of 41st & Elm',
    max_vendors: 30,
    is_published: true,
    is_cancelled: false,
    special_theme: 'Berry Festival',
    image_url: null,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
    vendor_count: 18,
  },
  {
    id: '3',
    title: 'Saturday Market - Flower Power',
    slug: 'saturday-market-flower-power',
    description: 'Spring is in full bloom! This week we\'re celebrating the beauty of locally grown flowers. Our flower vendors will have gorgeous bouquets, arrangements, and potted plants. Plus, a hands-on flower arranging workshop at 11 AM.',
    event_date: '2026-03-21',
    start_time: '09:00',
    end_time: '14:00',
    location: 'Market on 41st - Corner of 41st & Elm',
    max_vendors: 30,
    is_published: true,
    is_cancelled: false,
    special_theme: 'Flower Power',
    image_url: null,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
    vendor_count: 15,
  },
  {
    id: '4',
    title: 'Saturday Market - Farm to Table',
    slug: 'saturday-market-farm-to-table',
    description: 'Discover the farm-to-table journey! Meet the farmers behind your food, learn about sustainable growing practices, and sample fresh dishes prepared right at the market by local chefs using ingredients straight from our vendors.',
    event_date: '2026-03-28',
    start_time: '09:00',
    end_time: '14:00',
    location: 'Market on 41st - Corner of 41st & Elm',
    max_vendors: 30,
    is_published: true,
    is_cancelled: false,
    special_theme: 'Farm to Table',
    image_url: null,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
    vendor_count: 12,
  },
  {
    id: '5',
    title: 'Saturday Market - Earth Day Celebration',
    slug: 'saturday-market-earth-day',
    description: 'Celebrate Earth Day with us! Learn about composting, sustainable farming, and eco-friendly living. We\'ll have a seed swap station, recycling info booth, and kids\' nature crafts. Plus all your favorite vendors with the freshest local goodies.',
    event_date: '2026-04-04',
    start_time: '09:00',
    end_time: '14:00',
    location: 'Market on 41st - Corner of 41st & Elm',
    max_vendors: 30,
    is_published: true,
    is_cancelled: false,
    special_theme: 'Earth Day',
    image_url: null,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
    vendor_count: 8,
  },
]

export const vendorRegistrations: VendorRegistration[] = [
  { id: '1', vendor_id: '1', event_id: '1', status: 'approved', booth_number: 'A1', notes: null, products_preview: 'Heirloom tomatoes, salad greens, herbs', created_at: '2026-01-20T10:00:00Z', updated_at: '2026-01-20T10:00:00Z' },
  { id: '2', vendor_id: '2', event_id: '1', status: 'approved', booth_number: 'B3', notes: null, products_preview: 'Sourdough bread, cinnamon rolls, croissants', created_at: '2026-01-20T10:00:00Z', updated_at: '2026-01-20T10:00:00Z' },
  { id: '3', vendor_id: '3', event_id: '1', status: 'approved', booth_number: 'C2', notes: null, products_preview: 'Aged cheddar, fresh chèvre, whole milk', created_at: '2026-01-20T10:00:00Z', updated_at: '2026-01-20T10:00:00Z' },
  { id: '4', vendor_id: '4', event_id: '1', status: 'approved', booth_number: 'D1', notes: null, products_preview: 'Spring bouquets, tulips, daffodils', created_at: '2026-01-20T10:00:00Z', updated_at: '2026-01-20T10:00:00Z' },
  { id: '5', vendor_id: '5', event_id: '1', status: 'pending', booth_number: null, notes: null, products_preview: 'Tamales, fresh salsa, empanadas', created_at: '2026-01-25T10:00:00Z', updated_at: '2026-01-25T10:00:00Z' },
  { id: '6', vendor_id: '8', event_id: '2', status: 'approved', booth_number: 'A2', notes: null, products_preview: 'Strawberries, blueberries, berry preserves', created_at: '2026-01-20T10:00:00Z', updated_at: '2026-01-20T10:00:00Z' },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Maria Gonzalez',
    role: 'Market Regular',
    quote: 'Every Saturday at Market on 41st is like a little celebration. I love knowing exactly where my food comes from and chatting with the farmers who grew it. My kids look forward to it all week!',
  },
  {
    id: '2',
    name: 'David Chen',
    role: 'Neighborhood Resident',
    quote: 'The produce box is an absolute game-changer. For just $20, I get a beautiful selection of seasonal fruits and veggies that inspires my cooking all week long.',
  },
  {
    id: '3',
    name: 'Sarah Mitchell',
    role: 'Local Chef',
    quote: 'As a chef, quality ingredients are everything. The vendors at Market on 41st consistently deliver the freshest, most flavorful produce I can find anywhere in the city.',
  },
  {
    id: '4',
    name: 'James & Pat O\'Brien',
    role: 'Community Supporters',
    quote: 'This market has brought our neighborhood together in the most beautiful way. We\'ve made lifelong friends here, and our grandkids love picking out flowers and tasting fresh berries.',
  },
]

export const produceBoxItems: ProduceBoxItem[] = [
  { name: 'Seasonal Greens', icon: 'leaf', seasonal: true },
  { name: 'Heirloom Tomatoes', icon: 'apple', seasonal: true },
  { name: 'Fresh Herbs', icon: 'sprout', seasonal: true },
  { name: 'Root Vegetables', icon: 'carrot', seasonal: false },
  { name: 'Seasonal Fruit', icon: 'cherry', seasonal: true },
  { name: 'Farm Eggs', icon: 'egg', seasonal: false },
  { name: 'Artisan Bread', icon: 'croissant', seasonal: false },
  { name: 'Local Honey', icon: 'droplets', seasonal: false },
]

export const produceBoxFAQ: FAQItem[] = [
  {
    question: 'What\'s included in the $20 Produce Box?',
    answer: 'Each box contains a curated selection of 6-8 seasonal items sourced directly from our market vendors. Contents change weekly based on what\'s freshest and in season. You might find heirloom tomatoes, fresh herbs, seasonal berries, artisan bread, farm eggs, and more.',
  },
  {
    question: 'Can I customize my box?',
    answer: 'While we can\'t customize individual boxes (part of the magic is the surprise!), you can let us know about any allergies or dietary restrictions in the notes field when ordering. We\'ll do our best to accommodate.',
  },
  {
    question: 'How do I pick up my box?',
    answer: 'When you order, select your preferred pickup date corresponding to an upcoming market event. On market day, head to the Produce Box pickup table near the main entrance. Just give us your name and we\'ll have your box ready!',
  },
  {
    question: 'What if I can\'t make it to pickup?',
    answer: 'Life happens! If you can\'t pick up your box, you can send someone else with your order confirmation, or contact us at least 24 hours in advance to arrange an alternative pickup date.',
  },
  {
    question: 'How fresh is the produce?',
    answer: 'Everything in the box is harvested within 24-48 hours of your pickup date. Our vendors bring their freshest products specifically for the produce boxes. It doesn\'t get much fresher than this!',
  },
  {
    question: 'Do you offer subscriptions?',
    answer: 'Not yet, but we\'re working on it! For now, you can order a box each week through our website. Sign up for our newsletter to be the first to know when subscriptions launch.',
  },
]
